brothers_set = set(
    [
        "Erik Pfeffer",
        "Jack Spoleti",
        "Nithin Nambi",
        "Vikas Reddy",
        "Keagan Bergeron",
        "Aditya Goel",
        "Archer Sariscak",
        "Brendan Bullock",
        "Calvin Hughes",
        "Colin Wakefield",
        "Donovan Duong",
        # ADD FOR NEXT SEM: "Edwin Pavlovsky",
        "Griffith Uy",
        "Jack Giles",
        "Joseph Hutchison",
        "Kai Mckeown",
        "Karan Naiknavare",
        "Kurt Klaus",
        "Kyle Mcmahon",
        "Lanz Garcia",
        "Logan Gallant",
        "Max Schaffer",
        "Neil Burman",
        "Noah Tajalli",
        "Rikhil Konala",
        "Ryan Firebaugh",
        "Sanjeev Devarajan",
        "Sean Jordon",
        "Shiv Shah",
        "Shrey Varma",
        "Shreyes Varde",
        "Sohan Chokshi",
        "Tadhg Martinez",
        "Tarun Narahari",
        "Tyler Kempton",
        "Wyatt Riker",
        # ADD FOR NEXT SEM: "Yoonsuh Nam",
        "Zane Martinez",
        "Isaiah Ragsdale",
        "Will Phoone",
        "Jake Lawrence",
        # ADD BACK FOR NEXT SEM: "Adam Carita",
        "Azzan Tarik",
        "Carter Dinicola",
        "Gil Vadel",
        "Ian Stewart",
        "Matt Chytil",
        "Prod",
        "Rahul Tejwani",
        "Shubh Sharma",
        "Tyler Mcphee",
        "Luke Zic",
        "Daniel Son",
        "Daniel Hunter",
        "Arjun Pinto",
        "Yash Kapa",
        "Harry Shinkle",
    ]
)
